name = "Myrovh's Server Only Pack"
author = "myrovh"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d887bc232f2b9afdc6ed6193f779c3cbbb90f73e8436cea962bd4e0c49f4cce9"

[versions]
fabric = "0.14.12"
minecraft = "1.19"
