name = "Myrovh's Server Only Pack"
author = "myrovh"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbb9596b4bf02631e3d6f4e7851700f1b90353b47ebf77a94a8674573c2b1e2d"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
