name = "Myrovh's Server Only Pack"
author = "myrovh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a50d5f73b4dc2a79616b638af4e3c07c6e79c51bccb72ba7e59862b5b8887465"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
