name = "Myrovh's Server Only Pack"
author = "myrovh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "000a735fef8dc86951dccd0bdf7d54640c0de78b78fe4ce63e524de8b2a2e336"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
