name = "Myrovh's Server Only Pack"
author = "myrovh"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ee78790ee8791dfb9d7f926dade9785431e98e3b0920c0475438fb0d16efcec"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
