name = "Myrovh's Server Only Pack"
author = "myrovh"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b16f308d125511b535ac3d3acf04feb286fea25c887d5dae1ff2b20343186fd"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
