name = "Myrovh's Server Only Pack"
author = "myrovh"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c53ce539899276b9fbdfd1cac2fa3d7feffb8f598bf5e1444f18b1c0b08aec83"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
